Get visits based on venue name
sparkletown/sparkle pull request #1167
Opened 2021-02-12 12:38 UTC by thecadams

There were several users on the OG prod environment (emails available upon request please ask me) who were missing the `enteredVenueIds` key from their user record in Firestore.

This caused a recent event's analytics to misleadingly and incorrectly show as being attended by 10% of the believed attendance.

This change requires you to specify the venue name, but it will filter ALL users and ALL visits for those venue names.

With this, we were able to see a lot more data.

2021-02-15 05:07 UTC, 0xdevalias requested changes
Haven't deeply reviewed all of the code here, but wanted to make sure that this blocker was captured in case someone else is the one that reviews it.

2021-02-15 05:07 UTC, 0xdevalias commented on scripts/get-badges.ts
> -      .where("enteredVenueIds", "array-contains-any", venueIdsArray)
Not sure that this is a change we want to be doing here. The edgecase the changes in this PR was required for is definitely the exception, not the norm. So to have to process so much extra data every time is suboptimal.

This should probably only run when we need this 'special mode' or similar.

2021-02-15 23:36 UTC, 0xdevalias commented on scripts/get-badges.ts
> -    );
We may want to keep this formatted version of the time spent. Or alternately, include another column that includes this, as it's quite user-friendly data to include.

2021-02-15 23:49 UTC, 0xdevalias commented on scripts/get-badges.ts
> -    );
https://github.com/sparkletown/sparkle/pull/1167/commits/84b4c1a4a6bc5a9bd4dfd083287e9fac85ccd10f

2021-06-17 08:51 UTC, thecadams commented
Guessing this is stale, just doing a cleanup pass on my open PRs across all projects. Going to close but feel free to reopen if needed.

2021-06-17 08:51 UTC, closed without merging