Fix/png admin v2
sparkletown/sparkle pull request #1183
Opened 2021-02-16 13:09 UTC by margulies

In `admin_v2`, png files aren't accepted for upload. This seems to fix the issue.

2021-02-18 09:30 UTC, denisdimitrov approved these changes
LGTM!

2021-02-19 05:12 UTC, 0xdevalias commented
https://github.com/sparkletown/sparkle/pull/821 added this to `src/components/molecules/ImageInput/ImageInput.tsx` already, but it seems we have duplicate `ImageInput` components.

---

`src/components/molecules/ImageInput/ImageInput.tsx` is used by:

- `src/pages/Admin/Venue/DetailsForm.tsx`
- `src/pages/Admin/Venue/Rooms/RoomsForm.tsx`

`src/components/atoms/ImageInput/ImageInput.tsx` is used by:

- `src/pages/Admin/BasicInfo/BasicInfo.tsx`
- `src/pages/Admin/Details/Form/DetailsForm.tsx`
- `src/pages/Admin/Room/Edit/RoomEdit.tsx`
- `src/pages/Admin/Room/Modal/Item/Item.tsx`

From a basic skim of the code, looks less than trivial to unpick them and figure the better of the two, definitely OOS of this PR.

---

It looks like there is a `ACCEPTED_IMAGE_TYPES` in `src/settings.ts` though:

- https://github.com/sparkletown/sparkle/blob/staging/src/settings.ts#L126-L127

Which is currently used in:

- `src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx`

We should also use this in both of:

- `src/components/molecules/ImageInput/ImageInput.tsx`
- `src/components/atoms/ImageInput/ImageInput.tsx`

So that the one constant controls all of them.

We can technically also import from the `src/` folder in our scripts, so we could use this constant there as well for:

- `scripts/resize-images.ts`

2021-02-19 05:12 UTC, 0xdevalias requested changes
As per my comments in https://github.com/sparkletown/sparkle/pull/1183#issuecomment-781826235 can we refactor all of the locations to use `ACCEPTED_IMAGE_TYPES` from `serc/settings.ts` please.

2021-02-23 07:28 UTC, 0xdevalias approved these changes
Looks good, LGTM!

2021-02-23 07:28 UTC, 0xdevalias commented on src/components/molecules/ImageInput/ImageInput.tsx
> +import { ACCEPTED_IMAGE_TYPES } from "settings";
```suggestion
import { ACCEPTED_IMAGE_TYPES } from "settings";

```

2021-02-23 07:31 UTC, merged

2021-03-09 08:32 UTC, mobilevinay commented
is this really ready for QA in staging?