Fixes use profile z-index issue
sparkletown/sparkle pull request #1317
Opened 2021-04-12 05:04 UTC by mike-lvov

closes https://github.com/sparkletown/internal-sparkle-issues/issues/551

2021-04-12 05:46 UTC, 0xdevalias requested changes
Comments/suggestions/etc.

Not sure if the approach being taken here is necessarily the best way to resolve this issue.

See my notes on this issue in https://github.com/sparkletown/internal-sparkle-issues/issues/551#issuecomment-817428522

2021-04-12 05:46 UTC, 0xdevalias commented on src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
> +  z-index: ${reactionZIndex};
I believe emoji reactions and shout-outs explicitly had different layers by choice. This change seems to change/break that.

2021-04-12 05:46 UTC, 0xdevalias commented on src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
> +  z-index: ${reactionZIndex};
I believe emoji reactions and shout-outs explicitly had different layers by choice. This change seems to change/break that.

2021-04-12 05:46 UTC, 0xdevalias commented on src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
> -`;
Why was this moved? Presumably it worked fine where it was. Adds extra churn to this diff for little to no reason IMO.

2021-04-12 05:46 UTC, 0xdevalias commented on src/components/templates/PartyMap/components/Map/Map.scss
> +      z-index: 12;
Given this is in a scss file, it can use the `z()` helper with a properly named layer.

2021-04-12 05:46 UTC, 0xdevalias commented on src/components/molecules/MapPartygoerOverlay/MapPartygoerOverlay.tsx
> +      zIndex: "12",
Is the change added in `src/components/templates/PartyMap/components/Map/Map.scss` sufficient for this? If not, is there any reason we can't follow a similar pattern of setting the `z-index` layer within an scss class?

2021-04-12 05:46 UTC, 0xdevalias commented on src/scss/constants.scss
> +//   components/molecules/UserProfilePicture/UserProfilePicture.styles.ts (z-index: 10, 12)
What is the change here for? It seems if anything the `10` should be replaced with `12`, based on what I can see in the changes in `src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts`?

2021-04-12 08:31 UTC, 0xdevalias requested changes
Note that https://github.com/sparkletown/sparkle/pull/1318 fixes the core issue that this PR originally aimed to solve. It may still be worth keeping some of the other changes made in this PR though.

2021-04-14 06:14 UTC, mike-lvov commented
Given the layering issue is temporarily solved in https://github.com/sparkletown/sparkle/pull/1324 + we have a better refactor happening in https://github.com/sparkletown/sparkle/pull/1323, I don't think this PR has any value

2021-04-14 06:14 UTC, closed without merging