add support for emojis in chat using react-emoji-render
sparkletown/sparkle pull request #1394
Opened 2021-05-14 18:30 UTC by yarikoptic

Closes #1393 

This PR introduces base support, no completions/shortcuts etc for emoji's - just rendering

2021-05-15 04:21 UTC, 0xdevalias commented
> not sure if this would be an optimal solution if decided to proceed with emoji-picker (#1395) but may be they could be made to play together nicely.

@yarikoptic See my questions/discussion about this in https://github.com/sparkletown/sparkle/issues/1393#issuecomment-841595445 (let's figure out the path forward on that issue, then decide what to do for this PR)

2021-05-15 04:25 UTC, 0xdevalias requested changes
Officially marking this as 'changes requested' for now, till we decide the path we want to take forward on this.

All in all though, very cool addition, and keen to get it merged once we decide how we want to go about it! I'm pleasantly surprised at just how simple/little code needs to be changed for this!

2021-05-15 04:25 UTC, 0xdevalias commented on src/components/atoms/ChatMessage/ChatMessage.tsx
> +      </div>
As per https://github.com/sparkletown/sparkle/pull/1394#issuecomment-841597607, pending discussion in https://github.com/sparkletown/sparkle/issues/1393#issuecomment-841595445 to see if we want to just use `emoji-mart`, which has its own `Emoji` component for rendering emoji:

- https://github.com/missive/emoji-mart#emoji

2021-05-15 04:36 UTC, 0xdevalias commented
[OOS] While it's OOS for this PR, in future we could likely use this same lib/pattern to enhance our existing 'reactions' feature as well. Currently it just uses hardcoded emoji:

- https://github.com/sparkletown/sparkle/blob/staging/src/types/reactions.ts#L46-L103

Some of the related files:

- https://github.com/sparkletown/sparkle/search?q=reactions
  - https://github.com/sparkletown/sparkle/blob/staging/src/types/reactions.ts
  - https://github.com/sparkletown/sparkle/blob/staging/src/utils/reactions.ts
  - https://github.com/sparkletown/sparkle/blob/staging/src/hooks/reactions.tsx
  - https://github.com/sparkletown/sparkle/blob/staging/src/components/molecules/UserReactions/UserReactions.tsx
  - https://github.com/sparkletown/sparkle/blob/staging/src/components/templates/ReactionPage/ReactionList.tsx#L26
  - etc

We also have a backlog issue (scheduled to be worked on soon, after a couple of higher priority features) to clean up all of the 'send reaction' buttons/etc across the codebase into a single canonical component + logic in a hook, etc (currently each venue template has it's own duplicated code for rendering the 'reaction buttons' in places like the Jazz Bar, Auditorium (`Audience`), etc:

- 🔒 https://github.com/sparkletown/internal-sparkle-issues/issues/637

2021-05-17 21:06 UTC, yarikoptic commented
updated PR for current state of `staging` with support for multi-threaded chat.  And without URL's rendering support  ran into the case for which I believe I did test (manually) explicitly before but somehow `javascript://` now falls into the same trap as jitsi chat did:

![image](https://user-images.githubusercontent.com/39889/118556285-b1d8fb80-b731-11eb-8e8f-bfa54560506f.png)

but it happens only for `javascript://` and e.g. `short://` but not `http://` - I guess there is some ad-hoc exclusion of common protocols within -render.

2021-05-19 15:32 UTC, yarikoptic commented
overall I think this particular PR is superseded by #1383, so if that one is merged, this could be closed

2021-05-26 16:26 UTC, yarikoptic commented
I will just close this one -- it should be superseded by #1383 (markdown). We know where to find it if #1383 doesn't land

2021-05-26 16:26 UTC, closed without merging

2021-05-27 00:19 UTC, 0xdevalias commented
> I will just close this one -- it should be superseded by #1383 (markdown).

@yarikoptic Yup, agreed that #1383 seems like it will be our best overall path forward here.

Thanks for the initial exploration/version here though!

2021-05-27 00:20 UTC, 0xdevalias commented
Duplicate of #1383