Minor updates to ProfilePictureInput
sparkletown/sparkle pull request #1401
Opened 2021-05-15 15:23 UTC by soichih

I've moved profilepictureinput css to profilepictureinput component with minor style adjustment. This replaces the initial PR I made (1398).

![image](https://user-images.githubusercontent.com/923896/118368221-e3a26480-b56f-11eb-9f57-0fe93eb8b175.png)

2021-05-17 02:27 UTC, 0xdevalias requested changes
Hey @soichih,

Thanks for moving these styles into the appropriate scss file. I expect they were probably leftover in `src/pages/Account/Account.scss` as a legacy from a former refactor to split these components.

---

If you're open to it, it would be awesome if you could also rename these classes to follow our new BEM naming styles. You can read more about BEM here:

- http://getbem.com/naming/

This allows us to keep the styles 'namespaced' in a way that we can be sure they aren't inadvertently used/duplicated across the platform in unexpected places/ways.

At a very high level, the way we tend to use this is by naming the 'block' the same as the component, and then using the `__element` style for each of 'inner elements'.

We make use of the SCSS `&` helper to shorten what we need to type here:

- https://sass-lang.com/documentation/style-rules/parent-selector
- https://css-tricks.com/the-sass-ampersand/

So for this file, the structure would end up looking something like this:

```scss
.ProfilePictureInput {
  // main container styles

  &__preview {
    // styles
  }

  &__preview-container {
    // styles
  }

 // etc
}
```

This would then produce classes such as:

- `.ProfilePictureInput`
- `.ProfilePictureInput__preview`
- `.ProfilePictureInput__preview-container`
- etc

We would then need to update the appropriate locations in the component `.tsx` file to reference these renamed css classes.

Let me know if you have any questions or need any further guidance on this.

2021-05-17 02:27 UTC, 0xdevalias commented on src/pages/Account/Account.scss
> -}
[note] Moved to `src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss`, appears otherwise unchanged.

2021-05-17 02:27 UTC, 0xdevalias commented on src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
> +.profile-picture-preview {
[note] Only appears to be used by this component

2021-05-17 02:27 UTC, 0xdevalias commented on src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
> +.profile-picture-preview-container {
[note] Only appears to be used by this component

2021-05-17 02:27 UTC, 0xdevalias commented on src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
> +.profile-picture-input {
[note] Only appears to be used by this component

2021-05-17 02:27 UTC, 0xdevalias commented on src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
> +.profile-picture-button {
[note] Only appears to be used by this component

2021-05-17 02:27 UTC, 0xdevalias commented on src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
> +.profile-picture-upload-form {
[note] Only appears to be used by this component

2021-08-10 16:36 UTC, mike-lvov approved these changes
LGTM

2021-08-10 16:47 UTC, merged