BF: row could be 0 which renders condition False although a legit seat
sparkletown/sparkle pull request #1439
Opened 2021-05-24 21:51 UTC by yarikoptic

There is a separate check for FireLane (column) so should be ok in that regard
now that it would return True for 0, 0

Closes #1422

2021-05-25 01:04 UTC, 0xdevalias requested changes
Nice discovery @yarikoptic!

A couple of little improvements then this should be good to go!

2021-05-25 01:27 UTC, yarikoptic commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
Thanks! Applied suggestion. Will do the rest when get to laptop. Feel welcome to push such changes straight to any of my PRs in the future - they should be open for contributors

2021-05-25 01:36 UTC, 0xdevalias commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
> Feel welcome to push such changes straight to any of my PRs in the future - they should be open for contributors

Sounds good, shall keep it in mind.

For context, for similar reasons as you needing to get on a computer for it, it takes extra effort to switch context/clone your branch/commit the changes/push them back than it does to detail them as part of a review. Which is why I tend to write them here first.

2021-05-25 01:40 UTC, yarikoptic commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
Yeap, but between two of us causes duplication + delay. Anyways, that was just my FWIW and just me reflecting on how I approach PRs where I see that there is substantially more to be done outside of the diff at hand (although I did get burnt with such strategy too ;-)).

2021-05-25 02:39 UTC, 0xdevalias commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
Haha, yeah, that's fair enough :)

2021-05-25 03:25 UTC, yarikoptic commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
pushed

2021-05-25 06:16 UTC, 0xdevalias commented on src/components/templates/Audience/Audience.tsx
> +      return row != null && column != null;
Cool, thanks!

2021-05-25 06:17 UTC, 0xdevalias approved these changes
Code changes look good here, if we've clicked through this and are happy that it works as expected still, then LGTM!

**Edit:** Been fighting with our deploy preview environment script to try and get it working for non-sparkle PRs, which is why I haven't merged this yet.  Will probably end up cloning and testing This PR locally since it's taking so long, then try and fix that GitHub action/script more later.

2021-05-26 19:29 UTC, merged

2021-05-27 00:08 UTC, 0xdevalias commented
@mike-lvov Thanks for checking + merging this.

@yarikoptic Thanks for the bug fix!