[env/github] Replace back to label with back
sparkletown/sparkle pull request #1678
Opened 2021-06-28 06:51 UTC by alexey-petrov

As per https://github.com/sparkletown/internal-sparkle-issues/issues/855
* Replaced `back to {href}` with `back` label for github only

2021-06-28 06:52 UTC, 0xdevalias approved these changes
LGTM

2021-06-28 06:53 UTC, 0xdevalias requested changes
This definitely isn't all of the locations where this back text exists in the platform. I know for a fact at least the NavBar/similar also has it's own. And there may be more than that as well.

![image](https://user-images.githubusercontent.com/753891/123593166-8c133c00-d831-11eb-8438-ab3c871098b3.png)

May be other locations, didn't check deeply.

2021-06-28 07:05 UTC, alexey-petrov commented on src/pages/VenuePage/TemplateWrapper.tsx
> +            Back
as I can see this also pops up when user enters a venue, but it's a little different than the other places
guess it should be changed as well tho

2021-06-28 07:16 UTC, alexey-petrov commented
> This definitely isn't all of the locations where this back text exists in the platform. I know for a fact at least the NavBar/similar also has it's own. And there may be more than that as well.
> 
> ![image](https://user-images.githubusercontent.com/753891/123593166-8c133c00-d831-11eb-8438-ab3c871098b3.png)
> 
> May be other locations, didn't check deeply.

should be fixed now, thanks

2021-07-05 14:44 UTC, yurii-lubynets approved these changes

2021-07-06 06:16 UTC, merged