[staging] Fixed removing parentId
sparkletown/sparkle pull request #1851
Opened 2021-07-15 14:30 UTC by dmitrii-zolotukhin

- [ ] Fixed: you cannot remove parentId from admin v1 when editing venue

2021-08-09 11:43 UTC, denisdimitrov requested changes

2021-08-09 11:43 UTC, denisdimitrov commented on src/pages/Admin/Venue/DetailsForm.tsx
> +          if (vals.parentId && sovereignVenueId && sovereignVenue) {
Move this outside into a const

2021-08-09 11:43 UTC, denisdimitrov commented on src/store/actions/SovereignVenue.ts
> +  payload: {},
This object has no purpose but I suppose payload is a required field. Can you check if you can make it optional somehow?

2021-09-24 07:34 UTC, dmitrii-zolotukhin commented on src/pages/Admin/Venue/DetailsForm.tsx
> +          if (vals.parentId && sovereignVenueId && sovereignVenue) {
already fixed

2021-11-19 10:34 UTC, closed without merging