updated get-badges analytics script
sparkletown/sparkle pull request #1866
Opened 2021-07-20 15:00 UTC by alexey-petrov

Data is now extracted in 3 different files

Change log:
Unique venue list is extracted into `uniqueVenues.csv`
All visited venues - `allVisits.csv`
All the necessary user data - `allData.csv`
Venue visit time format changed to `HH:MM:SS`

2021-11-20 00:40 UTC, whoaitsaimz commented
@colinhowe I am curious if this is @alexey-petrov's latest script that he has been using to provide us with some good analytics the past few months? I just ran the existing get-badges and it seemed like the older one. Perhaps as this is a script we can get this one merged through?

2021-11-22 10:33 UTC, colinhowe commented
Re-opening this PR. It is the updated script and this needs updating+merging.

2021-11-22 15:14 UTC, mike-lvov requested changes

2021-12-17 07:34 UTC, alexey-petrov commented on scripts/get-badges.ts
> +};
I'm merging duplicated users here
![image](https://user-images.githubusercontent.com/56254806/146506983-72bd8da5-bdee-4fa9-b41a-0507a2190a37.png)

2021-12-17 08:15 UTC, alexey-petrov commented on scripts/get-badges.ts
> +const getUsersWithWisits = async () => {
done a065a42

2021-12-22 11:09 UTC, colinhowe approved these changes

2021-12-24 11:47 UTC, merged