ADV3 -- add nav bar in advance setting and spaces place
sparkletown/sparkle pull request #1991
Opened 2021-08-17 07:24 UTC by ermiaSparkle

closes issue https://github.com/sparkletown/internal-sparkle-issues/issues/1026 and https://github.com/sparkletown/internal-sparkle-issues/issues/1020

2021-08-17 12:26 UTC, denisdimitrov requested changes
This is not adding the navigation bar, this just moves the advanced settings inside 'manage space' screen. 

You need to wrap the screen with <WithNavigationbar/> to add the navigation bar.

2021-08-17 15:13 UTC, denisdimitrov requested changes

2021-08-17 15:13 UTC, denisdimitrov commented on src/components/organisms/AdminVenues/AdminVenues.scss
> +  padding: 8%;
All of our paddings are with pixel values, please keep it consistent.

2021-08-17 15:13 UTC, denisdimitrov commented on src/components/organisms/AdminVenues/AdminVenues.scss
> +    padding: 1rem;
There is `%` `px` and `rem` in a single file for different padding values. Very confusing.

2021-08-17 15:13 UTC, denisdimitrov commented on src/components/organisms/AdminTabsBar/AdminTabsBar.tsx
> +        ? adminNGSettingsUrl(venueId)
It should be using the same route, not another one.
If I can access the spaces like this:
https://co-reality-staging--preview-pr-1991-4osrrjuw.web.app/admin-ng/venue/8mars/spaces
Then I should be able to access advanced settings like this:
https://co-reality-staging--preview-pr-1991-4osrrjuw.web.app/admin-ng/venue/8mars/advanced

In the current implementation it's another route which is incorrect.

Ideally you should show this to Sofi and have a conversation about it. IMO only the "Advanced" Should be moved here and the other 2 tabs should exist in the other route.

2021-10-05 05:17 UTC, ermiaSparkle commented
Duplicate of #2268

2021-10-05 05:17 UTC, closed without merging