[DRAFT] added emergency space view
sparkletown/sparkle pull request #2031
Opened 2021-08-20 15:42 UTC by alexey-petrov

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1017

2021-08-25 07:53 UTC, dmitrymarchuk requested changes

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +  const venue = useSelector(currentVenueSelectorData);
won't be needed if `useConnectCurrentVenueNg` is used

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +  }, [venue]);
This is repeated in a codebase. It needs to be extracted into a separate hook everywhere and not duplicated once more here. And maybe replaced with `useCss`:)

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +  dayjs.extend(advancedFormat);
This does not need to be called inside a component body. Just needs to be called once at a top-level scope.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +  }, [dayDifference, liveAndFutureEvents, firstScheduleDate]);
Can be extracted into a separate utility component (including wrapping `<ul>` tag) for the `EmergencyViewPage`

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +          .sort(eventTimeAndOrderComparator);
This is a duplicate of `NavBarSchedule.tsx` on line 144.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +            venue.config?.landingPageConfig.bannerImageUrl ??
can we use classes here?

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +        </div>
This is a duplicate of the code in `VenueLandingPage.tsx` starting on lines 93.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +      </div>
This is also duplicated from `VenueLandingPage.tsx`

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +        </div>
Can be extracted into a separate component.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +                tab.id === selectedTab ? "--active" : ""
use `classNames` lib

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +              onClick={() => updateTab(tab.id)}
`useCallback`. But better extracted into a separate component first not to pollute this one.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.tsx
> +          ) : (
can also be extracted

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewRoom.tsx
> +export default EmergencyViewRoom;
great small component!

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.scss
> +  z-index: 100;
I am not sure, but maybe sass function `z` needs to be used here.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/pages/EmergencyViewPage/EmergencyViewPage.scss
> +@import "scss/constants.scss";
Overall file comments:

- Duplicate styles need to be extracted (together with duplicates in `tsx` file)
- `px`, `%` and other literal values needs to be extracted into constants. If similar alread exist in `constants.scss` those should be picked.
- naming should be changed to conform to BEM convention:
  * `-` character as a separator between words
  * `__` as element indicator
  * `--` as mofificator indicator.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
> +  isShowDayDate: boolean;
It seems from current usages that these new properties either are all `true` or all `false`. Can be simplified to just one property then.

2021-08-25 07:53 UTC, dmitrymarchuk commented on src/components/molecules/ScheduleEventListNG/ScheduleEventListNG.scss
> +  &_transparent {
BEM naming

2021-08-25 08:56 UTC, dmitrymarchuk commented
@alexey-petrov I also checked out a branch but couldn't see the rooms on the Spaces tab on `EmergencyViewPage`. It should be like this but I didn't see any rooms.
![image](https://user-images.githubusercontent.com/16973041/130760508-4e35a8d0-8ba8-447e-aeb1-6958a881f4d8.png)

Can you please provide a reference URL or venue name where the added functionality can be viewed?

2021-08-28 17:51 UTC, sunny-viktoryia approved these changes
going to approve and merge with the thought to finish the review and create a follow-up PR if needed.

2021-08-28 17:54 UTC, merged