Refactors related venues usage
sparkletown/sparkle pull request #2307
Opened 2021-09-15 15:51 UTC by mike-lvov

Instead of using tree-like fetch of related venues, we utilize new `worldId` property of the venue which will be introduced by https://github.com/sparkletown/sparkle/pull/2295

Do not merge until https://github.com/sparkletown/sparkle/pull/2295 and the run of the script to assign world id to every venue

2021-09-16 14:21 UTC, dmitrymarchuk requested changes
Great work @mike-lvov!👍
Left some comments & requests.

2021-09-20 07:19 UTC, mike-lvov commented on src/utils/venue.ts
> +export const getSovereignVenue = (
This function is used as an implementation detail in the `useRelatedVenues` hooks.

Renamed in https://github.com/sparkletown/sparkle/pull/2307/commits/4fdee3459a48ef2dbbe3df9e2dc433cc5dd2634e

2021-09-20 07:20 UTC, mike-lvov commented on src/hooks/useRelatedVenues.tsx
> +      checkedVenueIds,
Renamed in https://github.com/sparkletown/sparkle/pull/2307/commits/4fdee3459a48ef2dbbe3df9e2dc433cc5dd2634e

It's legacy logic & this PR is only to make it work with new connection type

2021-09-20 07:21 UTC, mike-lvov commented on src/hooks/useRelatedVenues.tsx
> +  const { currentVenueId } = props ?? {};
there is already a separate useCurrentVenue(even 2 of them). The issue is that there are a lot of places where this hook is used to find a venue by its current venueId

2021-09-20 07:21 UTC, mike-lvov commented on src/api/venue.ts
>  export const fetchVenue = async (
Deleted in https://github.com/sparkletown/sparkle/pull/2307/commits/4fdee3459a48ef2dbbe3df9e2dc433cc5dd2634e

2021-09-20 07:22 UTC, mike-lvov commented on src/components/molecules/ScheduleVenueDescription/ScheduleVenueDescription.tsx
> +export interface ScheduleVenueDescriptionProps {}
Removed in https://github.com/sparkletown/sparkle/pull/2307/commits/4fdee3459a48ef2dbbe3df9e2dc433cc5dd2634e

2021-09-20 07:49 UTC, dmitrymarchuk commented on src/utils/venue.ts
> +export const getSovereignVenue = (
But it's in `utils` and is `export`ed so one might assume it's a global utility function.
You might move it to`useRelatedVenues` file and do not `export` it there.

2021-09-20 07:50 UTC, dmitrymarchuk approved these changes
LGTM

2021-09-20 08:30 UTC, merged