[Admin] fix edit and create space preview
sparkletown/sparkle pull request #2496
Opened 2021-10-28 09:16 UTC by denisdimitrov

Fixes the space edit and create preview and uses the correct image for background in admin dashboard.

Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1354

2021-11-01 11:00 UTC, goran-peoski-work requested changes
Few notes about refactor and an issue about the preview not updating without clicking save (unlike the world preview).

![sparkle-space-preview-01](https://user-images.githubusercontent.com/79229621/139661688-967a6208-0e18-48ab-bcdf-0169a11783e9.png)


![sparkle-world-preview-01](https://user-images.githubusercontent.com/79229621/139661677-cb09c06b-eead-4533-a221-ea3a74c2e83f.png)

2021-11-02 13:28 UTC, denisdimitrov commented on src/hooks/useCurrentSpace.ts
> +export const useCurrentSpace: ReactHook<
@goran-peoski-work The other hooks are using the old useConnect syntax and it's 'lagging' just like the world did. It's showing the previous venue data when opened. That's why I decided to add this.

2021-11-02 13:28 UTC, denisdimitrov commented on src/pages/Admin/Venue/VenueWizard/Create/VenueWizardCreate.tsx
> +      <Details state={state} dispatch={dispatch} />
I just copied the old code, it's not good or very optimized.

2021-11-02 14:01 UTC, goran-peoski-work commented on src/pages/Admin/Venue/VenueWizard/Create/VenueWizardCreate.tsx
> +      <Details state={state} dispatch={dispatch} />
What old code?

2021-11-02 14:02 UTC, goran-peoski-work commented on src/hooks/useCurrentSpace.ts
> +export const useCurrentSpace: ReactHook<
which comes to
👇 
> should they get a @deprecated / @debt comments?

2021-11-08 09:53 UTC, whoaitsaimz commented
This one will be outdated as soon as Alexey's PR gets reviewed & merged sparkletown/sparkle#2533

2021-11-08 12:08 UTC, denisdimitrov commented on src/pages/Admin/Venue/VenueWizard/Create/VenueWizardCreate.tsx
> +      <Details state={state} dispatch={dispatch} />
It's somewhere in the old PR's its really hard to find it, but this was basically the old implementation that was removed by me. I will improve this as much as possible.

2021-11-16 09:58 UTC, ermiaSparkle commented
@denisdimitrov Should we close this one ?

2021-11-22 14:51 UTC, denisdimitrov commented
The new design change makes this obsolete.

2021-11-22 14:51 UTC, closed without merging