add AdminTitleBar to manage space component
sparkletown/sparkle pull request #2607
Opened 2021-11-26 18:47 UTC by denisdimitrov

Adds AdminTitleBar component with the buttons and texts from the IA design.

Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1486

2021-11-29 10:58 UTC, goran-peoski-work requested changes
There is a way to solve this without injecting class names into `AdminTitleBar`. It is meant to be a single child (in the page, not just its parent component) so it can be safely targeted with `.AdminTitleBar` 
- https://github.com/sparkletown/sparkle/pull/2610

2021-11-29 12:36 UTC, alexey-petrov requested changes
A few strings to replace with constants

2021-11-29 12:36 UTC, alexey-petrov commented on src/components/organisms/AdminVenueView/AdminVenueView.tsx
> +              Delete space
let's use `SPACE_TAXON.lower`

2021-11-29 12:36 UTC, alexey-petrov commented on src/components/organisms/AdminVenueView/AdminVenueView.tsx
> +              Visit Space
`SPACE_TAXON.capital`

2021-11-29 15:24 UTC, goran-peoski-work approved these changes
Approve with expectation to resolve some issues through sub-PR merge to staging.

2021-11-30 08:45 UTC, denisdimitrov commented on src/components/organisms/AdminVenueView/AdminVenueView.tsx
> +              Visit Space
Fixed

2021-11-30 08:45 UTC, denisdimitrov commented on src/components/organisms/AdminVenueView/AdminVenueView.tsx
> +              Delete space
Fixed.

2021-11-30 09:11 UTC, alexey-petrov approved these changes
LGTM

2021-11-30 09:36 UTC, merged