Wrap the `showShoutouts` toggler into `TesterRestricted`
sparkletown/sparkle pull request #2675
Opened 2021-12-07 15:29 UTC by goran-peoski-work

Temporarily puts 
- https://github.com/sparkletown/internal-sparkle-issues/issues/1510

to rest.

Untested, but checked the form validation and it didn't require the field to be provided.

2021-12-08 15:10 UTC, alexey-petrov approved these changes
LGTM

2021-12-10 10:03 UTC, colinhowe requested changes

2021-12-10 10:03 UTC, colinhowe commented on src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
> +                  <TesterRestricted>
I don't think this change is needed any more. I would love to see the schema changes committed next week though.

2021-12-29 11:01 UTC, goran-peoski-work commented
PR isn't needed. Some refactoring code can be re-used, so marking as scrap material and closing

2021-12-29 11:01 UTC, closed without merging