Makes chatbox display the latest messages
sparkletown/sparkle pull request #2928
Opened 2022-03-15 23:26 UTC by mike-lvov

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1760

2022-03-16 07:21 UTC, goran-peoski-work requested changes
I don't think just CSS reverting of the sort is the way to go. There might be a simple JS way to do it as well `itemsToDisplay.reverse()`

2022-03-16 07:21 UTC, goran-peoski-work commented on src/components/molecules/Chatbox/Chatbox.module.scss
> +  flex-direction: column-reverse;
I don't think depending on CSS is the way to go for displaying data properly. As a rule of thumb, data should be in order even if no styles are applied. 

So, can it be done in a way like `itemsToDisplay.sort().reverse()` or similar before outputing?

I mean, there are even nicer utilities from Flexbox, like `order` CSS property, but if we can display the data properly without resorting to style, I think we should use that.

2022-03-16 11:37 UTC, goran-peoski-work approved these changes
I took half an hour trying to figure this out. There might be something to do with the `inverse` prop of `<InfiniteScroll>` but this PR does solve the issue, even if in the CSS layer.

2022-03-16 11:37 UTC, merged

2022-03-18 15:05 UTC, whoaitsaimz commented
I dont think #176 is the correct issue number, but it didn't seem to auto-close it anyway, so prob not a big deal 

...unless someone else at Sparkle is as curious as me and clicks into related issues ;-)