🐛 Room show/hide on map if enabled/disabled in admin panel
sparkletown/sparkle pull request #852
Opened 2020-12-02 13:30 UTC by IvanBuljovcic

Show/Hide room on the partymap/themecamp if it is Enabled/Disabled in the Admin panel

2020-12-02 13:39 UTC, 0xdevalias requested changes
Can you please update the `<></>` returns to `null` as per in-lined comment, then this should be good to go!

2020-12-02 13:39 UTC, 0xdevalias commented on src/components/templates/Camp/components/MapRoomOverlay.tsx
> +  if (!room.isEnabled) return <></>;
Fragments are only really meant for grouping other sibling JSX elements together when we don't want to emit a `<div>`/similar to give them a common parent. In this case, we would want to return `null`

- https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering

2020-12-02 13:46 UTC, 0xdevalias commented
![](https://github.trello.services/images/mini-trello-icon.png) [Room turning on and off not working on partymap and themecamp templates](https://trello.com/c/689NmRaI/354-room-turning-on-and-off-not-working-on-partymap-and-themecamp-templates)

2020-12-02 14:55 UTC, 0xdevalias approved these changes
LGTM!

2020-12-02 15:00 UTC, merged

2020-12-03 02:13 UTC, thecadams commented
Great to see this merged. Quickly wondering, what about the third stage of a room when it’s disabled. Should we have it be at say 50% opacity and not clickable?